#!/usr/bin/env python3
"""Capture the text-line orientation classifier's input tensor and output.

Roadmap item: `DOCORI-001`.

This is the classifier's equivalent of `capture_preprocess_oracle.py`: it records
what the upstream preprocessing produces and what the real model answers, so the
Rust implementation is compared against a capture rather than against its own
reasoning. Two divergences in the classic path were found exactly this way.

The preprocessing sequence is transcribed from the **artifact's own
`inference.yml`**, not from upstream Python, because for this capability that is
where the contract lives — `docs/ORIENTATION_CONTRACT.md` records why:

    ResizeImage: size [160, 80]          # width, height
    NormalizeImage: scale 1/255,
                    mean [0.485, 0.456, 0.406],
                    std  [0.229, 0.224, 0.225]
    ToCHWImage
    Topk: label_list ["0_degree", "180_degree"]

Crops are deterministic synthetic images generated by formula, reproduced byte
for byte on the Rust side, plus the committed reading-order fixture and its
180-degree rotation — the pair that actually exercises what the classifier is
for.

Needs `numpy`, `cv2`, and `onnxruntime`. Nothing is downloaded.

Usage:
    python3 tools/capture_orientation_oracle.py <model dir> <output.json>
"""

from __future__ import annotations

import base64
import hashlib
import json
import struct
import sys
import zlib
from pathlib import Path

import numpy as np

CAPTURE_SCHEMA_VERSION = "paddleocr-rust/orientation-oracle-capture/v1"

# From PP-LCNet_x1_0_textline_ori/inference.yml.
RESIZE_WIDTH = 160
RESIZE_HEIGHT = 80
SCALE = 1.0 / 255.0
MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]
LABELS = ["0_degree", "180_degree"]

# Deterministic synthetic crops, matching the Rust side's `synthetic_crop`.
SYNTHETIC_SIZES = [(160, 80), (320, 48), (48, 160), (97, 53)]


def synthetic_crop(index: int, width: int, height: int) -> np.ndarray:
    """The same formula the Rust test uses, so both sides agree byte for byte."""
    x = np.arange(width, dtype=np.int64)[None, :, None]
    y = np.arange(height, dtype=np.int64)[:, None, None]
    c = np.arange(3, dtype=np.int64)[None, None, :]
    return ((x * 7 + y * 13 + c * 29 + index * 31) % 256).astype(np.uint8)


def read_png_bgr(path: Path) -> np.ndarray:
    import cv2

    data = np.frombuffer(path.read_bytes(), dtype=np.uint8)
    image = cv2.imdecode(data, cv2.IMREAD_COLOR)
    if image is None:
        raise SystemExit(f"cv2 could not decode {path}")
    return image


def preprocess(image: np.ndarray) -> np.ndarray:
    """The artifact's declared transform_ops, in order."""
    import cv2

    resized = cv2.resize(image, (RESIZE_WIDTH, RESIZE_HEIGHT))
    normalized = resized.astype("float32") * SCALE
    # `order: ''` means the mean and std apply positionally to the HWC image as
    # cv2 produced it, which is BGR. This is the same positional application the
    # detector uses, and the reason the Rust side can reuse that code.
    normalized = (normalized - np.array(MEAN, dtype="float32")) / np.array(
        STD, dtype="float32"
    )
    chw = normalized.transpose((2, 0, 1))
    return np.ascontiguousarray(chw, dtype="<f4")


def encode(tensor: np.ndarray) -> dict:
    raw = np.ascontiguousarray(tensor, dtype="<f4").tobytes()
    return {
        "shape": list(tensor.shape),
        "values_sha256": hashlib.sha256(raw).hexdigest(),
        "values_base64": base64.b64encode(raw).decode("ascii"),
    }


def rotate_180(image: np.ndarray) -> np.ndarray:
    import cv2

    return cv2.rotate(image, cv2.ROTATE_180)


def write_png(path: Path, image: np.ndarray) -> None:
    """Writes a BGR array as an 8-bit truecolour PNG, deterministically."""
    height, width = image.shape[:2]
    rgb = image[:, :, ::-1]
    raw = bytearray()
    for row in range(height):
        raw.append(0)
        raw += rgb[row].tobytes()

    def chunk(kind: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body))
            + kind
            + body
            + struct.pack(">I", zlib.crc32(kind + body) & 0xFFFFFFFF)
        )

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    model_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])

    import onnxruntime

    model = model_dir / "inference.onnx"
    session = onnxruntime.InferenceSession(
        str(model), providers=["CPUExecutionProvider"]
    )
    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name

    cases = []
    for index, (width, height) in enumerate(SYNTHETIC_SIZES):
        cases.append((f"synthetic-{index}", synthetic_crop(index, width, height)))

    upright = read_png_bgr(Path("tests/fixtures/classic-v1-e2e-reading-order/input.png"))
    cases.append(("reading-order-upright", upright))
    cases.append(("reading-order-rotated", rotate_180(upright)))

    records = []
    for name, image in cases:
        tensor = preprocess(image)
        batch = tensor[np.newaxis, :]
        probabilities = session.run([output_name], {input_name: batch})[0]
        row = np.asarray(probabilities[0], dtype="<f4")
        winner = int(np.argmax(row))
        records.append(
            {
                "case": name,
                "source_hwc_shape": list(image.shape),
                "source_bgr_sha256": hashlib.sha256(
                    np.ascontiguousarray(image).tobytes()
                ).hexdigest(),
                "input": encode(batch),
                "output": encode(row),
                "label": LABELS[winner],
                "score": float(row[winner]),
            }
        )
        print(f"{name}: {LABELS[winner]} {float(row[winner]):.6f}")

    document = {
        "capture_schema_version": CAPTURE_SCHEMA_VERSION,
        "model": {
            "name": "PP-LCNet_x1_0_textline_ori",
            "sha256": hashlib.sha256(model.read_bytes()).hexdigest(),
            "input_name": input_name,
            "output_name": output_name,
        },
        "preprocess": {
            "resize": [RESIZE_WIDTH, RESIZE_HEIGHT],
            "scale": SCALE,
            "mean": MEAN,
            "std": STD,
            "labels": LABELS,
        },
        "records": records,
    }
    output.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
